### ISSUE TITLE
Hayseed cards won't create one Orb Slot, in case of the player having 0 Orb Slots

### ISSUE THREAD

**Issue by Clauvin** [jwoolley/simpleton-mod#13]
Yes, it is me, with more multicolor shenanigans! :p

**What's happening:** thanks to Custom Game, players can add Hayseed cards to their runs. Some Hayseed cards Plant vegetables and fruits, in a similar way to Defect cards Channel Orbs.

The main difference between both, and I don't know if that's intentional or not, is that at modded games (don't know if base game does that too), Channelling when you have 0 Orb Slots give you 1 Orb Slot on that moment and it stays with you until the end of the run.

It allows characters that usually wouldn't be able to manipulate Orbs to have at least a bit of fun with them, but in the case of Hayseed cards, no Orb Slots are created.

**How to reproduce it:**

Using BaseMod and Hayseed mods:

1 - Start a game with Silent.
2 - Start a combat.
3 - Using console, add to your hand an Artichoke and Ball Lighting.
4 - Use Artichoke first, then Ball Lightning. The Artichoke won't generate an Orb Slot, Ball Lightning will.

**Comment by jwoolley** [comment]
Fixed with 6422b62864018023d7543e00ac3101f927960dcd.
